import os
import pandas as pd
import subprocess
import sys
import glob

def run_merge_and_extract():
    # Get the directory of the current script
    script_dir = os.path.dirname(os.path.abspath(__file__))
    merged_list = []
    
    print("Starting data merge and company name extraction process...")
    print(f"Working directory: {script_dir}")

    # Discover CSV files generated by scrape_year function in the current directory
    # Exclude the final merged file 'complete_dataset_jp.csv' if it already exists
    csv_files = glob.glob(os.path.join(script_dir, "*.csv"))
    
    # Filter out 'complete_dataset_jp.csv' as it's an output file, not an input for merging
    csv_files = [f for f in csv_files if os.path.basename(f) != "complete_dataset_jp.csv"]
    csv_files.sort() # Sort to ensure consistent merging order

    if not csv_files:
        print("No individual year CSV files found in the directory to merge (e.g., 1998.csv, 1999.csv).")
        print("Please ensure 'data-grabber-all.py' has been run to scrape data first, or check the directory.")
        # We will still attempt to run the extractor script, as it might work with other inputs
    else:
        print(f"Found {len(csv_files)} individual CSV files for merging.")
        for csv_file in csv_files:
            try:
                # Read each CSV file, paying attention to encoding
                df = pd.read_csv(csv_file, encoding='utf-8-sig')
                merged_list.append(df)
                print(f"  - Loaded {os.path.basename(csv_file)}")
            except Exception as e:
                print(f"Error reading CSV {os.path.basename(csv_file)}: {e}")

        if merged_list:
            # Concatenate all loaded DataFrames
            complete_df = pd.concat(merged_list, ignore_index=True)
            complete_path = os.path.join(script_dir, "complete_dataset_jp.csv")
            # Save the merged DataFrame to a new CSV file
            complete_df.to_csv(complete_path, index=False, encoding='utf-8-sig')
            print(f"Completed! Merged dataset saved to {complete_path}. Total records: {len(complete_df)}")
        else:
            print("No data was successfully loaded from individual CSVs for merging.")

    # 自動実行：会社名抽出スクリプト (extract_company_names.py)
    print("\n" + "=" * 60)
    print("会社名抽出スクリプト（extract_company_names.py）を開始します...")
    print("=" * 60)
    
    extractor_script = os.path.join(script_dir, "extract_company_names.py")
    if os.path.exists(extractor_script):
        try:
            # Execute the script using the current Python interpreter
            # check=True will raise CalledProcessError if the script exits with a non-zero status
            subprocess.run([sys.executable, extractor_script], check=True)
            print("\n会社名抽出が完了しました。")
        except subprocess.CalledProcessError as e:
            print(f"\n会社名抽出スクリプトの実行中にエラーが発生しました: {e}")
        except FileNotFoundError:
            print(f"\nエラー: Python インタープリタ '{sys.executable}' が見つかりません。")
        except Exception as e:
            print(f"\n会社名抽出スクリプトの実行中に予期せぬエラーが発生しました: {e}")
    else:
        print(f"\nエラー: 抽出スクリプトが見つかりませんでした: {extractor_script}")

if __name__ == "__main__":
    run_merge_and_extract()
